-- SQL Lesson 10: Queries with aggregates (Pt. 1)
-- Find the longest time that an employee has been at the studio
-- For each role, find the average number of years employed by employees in that role
-- Find the total number of employee years worked in each building
