-- SQL Lesson 4: Filtering and sorting Query results
-- List all directors of Pixar movies (alphabetically), without duplicates
-- List the last four Pixar movies released (ordered from most recent to least)
-- List the first five Pixar movies sorted alphabetically
-- List the next five Pixar movies sorted alphabetically
