-- SQL Lesson 6: Multi-table queries with JOINs
-- Find the domestic and international sales for each movie
-- Show the sales numbers for each movie that did better internationally rather than domestically
-- List all the movies by their ratings in descending order
